In [2]:
import pandas as pd
import numpy as np
import os
from sklearn.linear_model import  LinearRegression
from sklearn.feature_selection import f_regression

# Load the data

In [17]:
data=pd.read_csv('data.csv', nrows=100)
data.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

# Load dependent and independent variable

In [18]:
x=data[['R&D Spend','Administration','Marketing Spend']]
y=data['Profit']

# Create instance of LinearRegerssion

In [19]:
reg= LinearRegression()

In [20]:
reg.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [21]:
reg.coef_

array([ 0.80571505, -0.02681597,  0.02722806])

In [22]:
reg.intercept_

50122.19299202236

In [23]:
r2=reg.score(x,y)

In [24]:
r2

0.9757125022048049

In [25]:
x.shape

(100, 3)

In [26]:
n=x.shape[0]
p=x.shape[1]
n

100

In [27]:
adjusted_r2=1-(1-r2)*(n-1)/(n-p-1)
adjusted_r2

0.974953517898705

Run F_Regression to get the 'p' and 'F' values. In this linear regresion for every dependent variable with independent variable and find f and p-values

In [28]:
f_regression(x,y)

(array([3619.21649991,   10.47421038,  250.92955901]),
 array([3.46981268e-79, 1.65171511e-03, 8.93427390e-29]))

In [31]:
f_values=f_regression(x,y)[0].round(3)
p_values=f_regression(x,y)[1].round(3)

In [32]:
reg_summary=pd.DataFrame(data=x.columns.values,columns=['features'])

In [35]:
reg_summary

features
0        R&D Spend
1   Administration
2  Marketing Spend

In [37]:
reg_summary['Coefficients']=reg.coef_
reg_summary['p_values']=p_values
reg_summary['f_values']=f_values

In [38]:
reg_summary

features  Coefficients  p_values  f_values
0        R&D Spend      0.805715     0.000  3619.216
1   Administration     -0.026816     0.002    10.474
2  Marketing Spend      0.027228     0.000   250.930